### ISSUE TITLE
Has the project been totally abandoned?

### ISSUE THREAD

**Issue by cxspxr** [upsidelab/voicecommerce#2]

**Comment by rafalcymerys** [comment]
Nope, it's serves its role as a base for voice + magento integrations .If you feel like there's anything missing - feel free to contribute :) 

In terms of plans for future development: we're currently working on a highly-conceptual level. While working with clients we've noticed some common patterns, especially around Google Assistant. We just need to confirm that they're generic enough to implement them in here.
